<?php if ($banner = $this->getBannerData()) : ?>
    <?php $_id = $this->getHtmlId($banner->getIdentifier()); ?>
    <div class="easybanner-banner <?php echo $this->getBannerClassName() ?>" id="<?php echo $_id ?>">
    <?php if ('image' === $banner->getMode()) : ?>
    <?php
        $onclick = '';
        $options = '\'\'';
        if ($banner->getTarget() == 'popup') {
            $options = '\'width=600,height=400\'';
        }
        if ($banner->getTarget() != 'self') {
            $onclick = 'onclick="return !window.open(this.href, \'easybanners'.$banner->getBannerId().'\', '.$options.')"';
        }

        $height = $banner->getHeight();
        $width  = $banner->getWidth();
    ?>
        <a class="easybanner-image-link" rel="nofollow" href="<?php echo $this->getUrl() . $this->getBannerUrl() ?>" title="<?php echo $banner->getTitle() ?>" <?php echo $onclick ?>>
        <?php if(!$banner->getResizeImage()): ?>
            <?php
                $style = '';
                if (!empty($width)):
                    $style = 'width: ' . $width . 'px';
                elseif (!empty($height)):
                    $style = 'height: ' . $height . 'px';
                endif;
            ?>
            <img src="<?php echo $this->getBannerImage() ?>" style="<?php echo $style ?>" alt="<?php echo $block->escapeHtml($banner->getTitle()) ?>" />
        <?php else: ?>
            <img src="<?php echo $this->resizeImage($width, $height) ?>"
            <?php if ($banner->getRetinaSupport()) : ?>
                srcset="<?php echo $this->resizeImage($width, $height) ?> 1x, <?php echo $this->resizeImage($width * 2, $height * 2) ?> 2x"
            <?php endif ?>
                width="<?php echo $width ?>"<?php echo $height ? " height='$height'" : '' ?>
                alt="<?php echo $block->escapeHtml($banner->getTitle()) ?>"
            />
        <?php endif; ?>
        </a>
    <?php else : ?>
        <?php echo $this->getBannerHtml() ?>
    <?php endif; ?>
    </div>
<?php endif; ?>